auditor/network.go, constructor/containers.go, constructor/queries.go, model/connection.go
This PR adds the "TCP retransmissions" chart to the Network inspection. The chart displays the number of retransmitted TCP segments per upstream service.
=> TCP retransmissions

constructor/elasticache.go, constructor/rds.go, front/src/views/ProjectStatus.vue, model/application.go, model/application_types.go, model/node.go
This PR introduces a suggestion to install [aws-agent](https://github.com/coroot/coroot-aws-agent) when external services using the following ports are detected within the AWS cluster: 
* Port 5432 (RDS for Postgres)
* Port 3306 (RDS for MySQL)
* Port 11211 (ElastiCache for Memcached)
* Port 6379 (ElastiCache for Redis)
=> A suggestion to install aws-agent to instrument AWS RDS and AWS ElastiCache 

notifications/teams.go
Disable validation webhook for msteams https://github.com/atc0005/go-teams-notify/tree/master#disable-webhook-url-prefix-validation
=> Disable validation webhook for msteams

cache/client.go, cache/compaction.go, cache/updater.go, timeseries/timeseries.go
- fix cache step calculation
- use max step in compaction
- limit backfill by 4h
- don't overwrite data with NaNs
=> prometheus cache improvements

api/views/overview/nodes.go, constructor/constructor.go, constructor/fargate.go, constructor/k8s.go, constructor/queries.go, front/src/components/Table.vue, model/node.go, model/table.go
This PR introduces initial support for AWS Fargate. Coroot uses metrics collected from the Cadvisor integrated into Fargate "nodes".
=> initial support for AWS Fargate

deploy/install.sh
This PR adds a script to install Coroot on a Linux node and run it as a systemd service. Tested on Ubuntu, Debian, and CentOS
=> add install script

api/views/overview/health.go, auditor/auditor.go, auditor/deployments.go, auditor/dns.go, auditor/slo.go, constructor/containers.go, constructor/queries.go, front/src/views/Health.vue, model/audit_report.go, model/check.go, model/container.go, model/table.go
This PR introduces DNS monitoring capability in Coroot. This feature is based on metrics gathered by [coroot-node-agent](https://github.com/coroot/coroot-node-agent) using eBPF. Coroot has three built-in inspections to highlight the most common DNS issues out-of-the-box:
1. **DNS latency**: This inspection checks the 95th percentile of DNS response time. By default, the threshold is set at 100ms, but you can easily adjust it for a particular app or for the entire project.
2. **DNS server errors**: This check identifies situations when a DNS server responds with an error.
3. **DNS NXDOMAIN errors**: This check highlights scenarios when the application receives no results for certain domains, such as when a Kubernetes headless service has no ready endpoints.
=> DNS monitoring

api/api.go, api/forms/forms.go, api/views/application/application.go, api/views/applications/categories.go, api/views/applications/custom_applications.go, api/views/views.go, constructor/constructor.go, constructor/containers.go, constructor/elasticache.go, constructor/k8s.go, constructor/rds.go, db/project.go, front/src/api.js, front/src/components/AppMap.vue, front/src/components/ApplicationFilter.vue, front/src/views/CustomApplications.vue, front/src/views/Project.vue, main.go, model/application.go, model/custom_application.go, model/world.go
This PR introduces custom applications in Coroot. You can now create applications manually and associate specific instances with them. This is useful when the built-in grouping doesn't accurately reflect your system.
For example, if you have 10 Apache HTTPD instances running on 10 nodes as systemd services, Coroot typically groups them into one application by their unit name. If this grouping isn't accurate for your setup, you can create custom applications and define the instance mapping to better match your system design.
=> Custom applications

api/views/configs/configs.go, api/views/overview/health.go, auditor/storage.go, front/src/components/CheckConfigForm.vue, front/src/components/CheckDetails.vue, front/src/views/Health.vue, model/check.go
Coroot now uses the I/O load metric (total I/O latency) to identify storage performance issues. Previously, we relied on I/O utilization, which measures the time the disk performs at least one query. This method was accurate for spinning HDDs but is less effective for modern SSDs, which can handle multiple queries simultaneously.
To address this, Coroot sets a default threshold of 5 seconds/second for I/O load. If a disk performs more than 5 I/O requests in parallel, it is flagged as having high I/O load. This threshold is optimal for most average SSDs on the market. However, if you use higher-performance storage, you can easily adjust this threshold for specific applications, databases, or entire projects.
=> using I/O load instead of utilization percentage for highlighting I/O issues

api/views/overview/service_map.go, model/application_category.go
1. Use client's app category instead of the default `application` category
2. Add patterns to improve matching of auxiliary apps to the `control-plane` category
=> App categories improvements

api/views/application/application.go, api/views/overview/service_map.go, auditor/network.go, constructor/containers.go, constructor/queries.go, model/connection.go, utils/format.go
Coroot now shows Service-to-Service traffic. The metrics are measured at the TCP level and don't include IP and TCP headers, which can add 2-4%. These metrics only reflect the TCP payload size.
Traffic is show on Service Map:
Application Dependency Map:
and in the Network inspection details:
=> Service-to-service traffic

api/views/overview/costs.go, api/views/overview/types.go, cloud-pricing/manager.go, cloud-pricing/model.go, constructor/nodes.go, front/src/components/ApplicationsCosts.vue, front/src/components/NodesCosts.vue, model/node.go, utils/ip.go
Coroot now calculates data transfer costs for cross-AZ traffic and Internet Egress.
Nodes:
Applications:
Limitations:
* Only the TCP payload is considered, without TCP/IP headers
* Only outbound TCP connections are taken into account 
* The free tier is not supported yet
* The first tier of Internet Egress pricing is used
* Cross-region data transfer pricing is not taken into account
=> add `Internet egress` and `Cross-AZ` data transfer costs breakdown

collector/logs.go
=> prevent saving log records with invalid timestamps to ClickHouse

model/application_category.go
Added namespaces to the `ApplicationCategoryControlPlane`:
- `keptn-system` - Cloud-native application life-cycle orchestration. Keptn automates your SLO-driven multi-stage delivery and operations & remediation of your applications.
- `kyverno` - Cloud Native Policy Management
- `litmus` - Litmus helps SREs and developers practice chaos engineering in a Cloud-native way. Chaos experiments are published at the ChaosHub (https://hub.litmuschaos.io/). Community notes is at https://hackmd.io/a4Zu_sH4TZGeih-xCimi3Q
Added namespaces to the `ApplicationCategoryMonitoring`:
- `loki` - Like Prometheus, but for logs
- `observability` - used by various companies and applications as a naming convention for monitoring components
=> add additional patterns to the app category

go.mod, go.sum
`github.com/grafana/pyroscope-go/godeltaprof` dependency prevents `coroot` from building with Go 1.23. This is solved by bumping the version to more recent one. ( https://github.com/grafana/pyroscope-go/issues/117 )
fixes #356
=> Fix broken build on Go 1.23

deploy/install.sh
Hello.
I ran the `deploy/install.sh` according to the documentation, but I got a permission error.
```
seinoyu@ubuntu2404:~/coroot$ uname -a
Linux ubuntu2404 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
seinoyu@ubuntu2404:~/coroot$ curl -sfL https://raw.githubusercontent.com/coroot/coroot/main/deploy/install.sh | \
BOOTSTRAP_PROMETHEUS_URL="http://127.0.0.1:9090" \
BOOTSTRAP_REFRESH_INTERVAL=15s \
BOOTSTRAP_CLICKHOUSE_ADDRESS=127.0.0.1:9000 \
sh -
[INFO]  Creating uninstall script /usr/bin/coroot-uninstall.sh
*** INSTALLING coroot ***
[INFO]  Finding the latest release
[INFO]  The latest release is v1.6.8
[INFO]  Downloading binary
[INFO]  Installing to /usr/bin/coroot
[INFO]  env: Creating environment file …
```
=> [Bug]: Fix install failed by Permission denied.

docs/docs/installation/k8s-operator.md
Correct version:
kubectl explain Coroot.spec.agentsOnly
corootURL	<string>
<no description>
=> fix: changed the field coroot Url name to the correct version

docs/docs/installation/requirements.md
Fixes https://github.com/coroot/coroot-node-agent/issues/106
Update the documentation to specify that the minimum supported Kernel version is 5.1.
=> Update requirements.md to update the minimum required Linux kernel version.

deploy/docker-compose.yaml
At some point `clickhouse` started to limit the "default" user to access from localhost only (127.0.0.1 / ::1) but coroot expects to be able to access `clickhouse` from the `coroot` container via docker networking.
fixes #534
=> docker-compose: disable user setup in clickhouse entrypoint script

docs/docs/installation/k8s-operator.md
This update to the Coroot Operator introduces the ability to specify custom annotations for the Kubernetes Service resource that the operator manages. This enhancement provides users with greater flexibility to integrate the coroot service with other tools or to leverage specific Kubernetes features that rely on service annotations.
=> docs: add annotations section for Service in k8s-operator installation guide

docs/docs/tracing/opentelemetry-java.md
I used the example from your documentation and observed that my Java process was filling the logs with exceptions about not being able to deliver logs via OpenTelemetry. This disables the logs feature of the agent.
Alternative:
I can rework this to instead also send logs via OpenTelemetry, please comment if you like it that way.
=> Disable logs exporter in Java example for OpenTelemetry 

config/config.go
This allows injecting secrets and other values from environment variables into the configuration.
=> config: enable environment variable substitution

notifications/webhook.go
* Strings in golang are emtpy "" by default which can cause problems
=> fix: Check for empty strings for basic auth

docs/docs/installation/k8s-operator.md
if we use variable "spec.ai.openaiCompatible.baseUrl", we catching error "cannot patch "coroot" with kind Coroot: Coroot.coroot.com "coroot" is invalid: spec.ai.openaiCompatible.baseURL: Required value"
=> fix helm error

api/api.go, clickhouse/clickhouse.go
Since upgrading to v1.13.0, the program has encountered a panic issue.
Here is the log where the issue occurred:
```
http: panic serving *****: runtime error: invalid memory address or nil pointer dereference
goroutine 261 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1947 +0xbe
panic({0x13b0be0?, 0x32729d0?})
/usr/local/go/src/runtime/panic.go:792 +0x132
github.com/coroot/coroot/clickhouse.(*Client).Close(...)
/tmp/src/clickhouse/clickhouse.go:102
github.com/coroot/coroot/api.(*Api).Overview(0xc001789ec0, {0x29ca278, 0xc007f58380}, 0xc007f7a000, 0xc007c97310)
/tmp/src/api/api.go:374 +0xc3b
main.main.(*Api).Auth.func15({0x29ca278, 0xc007f58380}, 0xc007f7a000)
/tmp/src/api/auth.go:76 +0x107
net/http.HandlerFunc.ServeHTTP(0x13d93c0?, {0x29ca278?, …
```
=> fix: should check ch not nil before ch.Close()
