- auditor/logs.go
> Fix typo in log message

- auditor/auditor.go
- auditor/slo.go
- constructor/containers.go
- constructor/queries.go
- model/application_types.go
- model/chart.go
This PR adds support for the NATS messaging platform.
> NATS support

- constructor/containers.go
This PR fixes Heatmaps when some histogram buckets are empty
> Don't skip connection metrics with zeroes

- auditor/auditor.go
- auditor/dotnet.go
- constructor/containers.go
- constructor/dotnet.go
- constructor/queries.go
- model/application.go
- model/audit_report.go
- model/check.go
- model/dotnet.go
- model/instance.go
This PR introduces .NET runtime inspection based on metrics gathered by `node-agent`.
> .NET runtime monitoring

- api/forms/forms.go
- db/integrations.go
- front/src/components/IntegrationFormWebHook.vue
- front/src/views/IntegrationForm.vue
- model/application_deployment.go
- notifications/incidents.go
- notifications/notifications.go
- notifications/webhook.go
- watchers/deployments.go
Hi! PR include integration via webhook for sending messages about incidents and deployments.
Message formatting is implemented via "text/template".
If you have any comments, I will be happy to correct them.
@Jipok and I checked integrations with telegram and mattermost
I like coroot but without integrations with these platforms it becomes less useful for us
> Add webhook integration

- model/application_category.go
Added namespace: linkerd, vault, keda, keycloak, metrics-server
Removed duplicate of istio-system namespace
> add additional patterns to the `control-plane` app category

- api/api.go
- api/views/overview/traces.go
- api/views/tracing/tracing.go
- clickhouse/traces.go
- front/src/components/Heatmap.vue
- front/src/views/Traces.vue
- front/src/views/Tracing.vue
> traces: add custom filters to the `Traces` view

- constructor/constructor.go
- constructor/containers.go
- constructor/fqdn.go
> using semi-consistent FQDNs for IPs resolving to multiple domains

- api/views/overview/health.go
- auditor/auditor.go
- auditor/python.go
- constructor/containers.go
- constructor/python.go
- constructor/queries.go
- model/application.go
- model/application_types.go
- model/audit_report.go
- model/check.go
- model/instance.go
- model/python.go
This PR introduces Python GIL (Global Interpreter Lock) monitoring feature. The metrics are gathered by the node-agent using eBPF, which does not require any instrumentation or changes to the application code.
> Python GIL (Global Interpreter Lock) monitoring

- model/application_types.go
https://coroot-community.slack.com/archives/C0443R3BW2G/p1719932016308619
> lower the priority for the Envoy app type

- api/views/overview/nodes.go
- front/src/components/Table.vue
- model/table.go
* show aggregated network bandwidth instead of per-interface
* collapse node IPs list
> make nodes view more compact 

- auditor/network.go
> enhance view of external services on dependency map

- api/views/application/application.go
- api/views/overview/overview.go
- api/views/overview/service_map.go
- constructor/constructor.go
- constructor/containers.go
- front/src/components/AppMap.vue
- front/src/components/AppPreferences.vue
- front/src/components/ServiceMap.vue
- front/src/views/ApplicationCategories.vue
- front/src/views/Overview.vue
- model/world.go
> add quick links for application categories configuration

- api/api.go
- api/ctx.go
- front/src/App.vue
- front/src/api.js
- front/src/components/RcaItem.vue
- front/src/utils/format.js
- front/src/views/Incident.vue
- front/src/views/Incidents.vue
- front/src/views/Overview.vue
- front/src/views/RCA.vue
- main.go
- notifications/notifications.go
> Root Cause Analysis UI components

- front/src/views/OpenTelemetryIntegration.vue
- front/src/views/Traces.vue
> add documentation on configuring OpenTelemetry SDKs and the collector to send traces to Coroot

- api/api.go
- api/forms/forms.go
- clickhouse/clickhouse.go
- clickhouse/logs.go
- clickhouse/profiles.go
- clickhouse/queries.go
- clickhouse/traces.go
- collector/collector.go
- collector/config.go
- collector/logs.go
- collector/migrate.go
- collector/profiles.go
- collector/traces.go
- constructor/k8s.go
- go.mod
- go.sum
> add support for clustered ClickHouse

- front/src/App.vue
> Fix typo for sign out

- docs/docs/installation/docker.md
Hello.
When I installed it using docker compose, coroot-cluster-agent also started.
> [Fix Docs]: Installation with docker compose.

- api/views/logs/logs.go
- api/views/overview/traces.go
- api/views/tracing/tracing.go
- clickhouse/logs.go
- clickhouse/traces.go
- collector/collector.go
- collector/migrate.go
- db/db.go
- front/src/components/TracingSpan.vue
- front/src/views/Traces.vue
and fix for https://github.com/coroot/coroot/issues/433
> traces & logs: clickhouse queries optimization

- auditor/memory.go
Before this PR, Coroot detected memory leaks based on the total RSS of all application instances, which could be noisy in scenarios like scaling. Now, it detects leaks on a per-instance basis, reducing noise.
> memory: detect memory leaks on a per-instance basis

- clickhouse/traces.go
Fix for https://github.com/coroot/coroot/issues/449
> traces: handle nullish trace ids

- collector/migration.go
- config/config.go
- config/flags.go
- db/integrations.go
- front/src/views/IntegrationClickhouse.vue
Added option for modifying default TTL (7 days)  for logs, traces and profiles in clickhouse
> added TTL option for logs, traces and profiles in clickhouse

- cache/chunk/v4.go
> cache: limit label value size to MaxUint16

- collector/metrics.go
> collector: respond with HTTP-200 to prevent agent retries on Prometheus HTTP-400

- front/src/views/Incidents.vue
Fixing a trivial typo in the UI.
> Fixing typo s/budged/budget/g

- auditor/memory.go
> Memory: add a sub-chart with total memory by application instance (RSS+PageCache)

- api/api.go
- api/views/inspections/inspections.go
- front/src/components/CheckConfigSLOAvailabilityForm.vue
- front/src/components/CheckConfigSLOLatencyForm.vue
- front/src/components/CheckForm.vue
- front/src/views/Inspections.vue
- model/check.go
> make project-level SLO defaults configurable

- CONTRIBUTING.md
- dev.dockerfile
For build coroot without install npm localy
> add Dockerfile for dev

- config/flags.go
- front/src/components/PropagationMap.vue
- front/src/utils/format.js
- front/src/views/Incident.vue
- front/src/views/RCA.vue
- model/application_incident.go
- utils/stringset.go
> rca: add issue propagation map

- auditor/auditor.go
- auditor/nodejs.go
- constructor/constructor.go
- constructor/nodejs.go
- constructor/queries.go
- model/application.go
- model/application_types.go
- model/audit_report.go
- model/check.go
- model/instance.go
- model/nodejs.go
> add a Node.js inspection that tracks event loop blocked time
